### ISSUE TITLE
[Request]  tor-browser-bin

### ISSUE THREAD

**Issue by dandare1980** [chaotic-aur/packages#3174] opened 2024-05-27 18:32 UTC
### Package:

https://aur.archlinux.org/packages/tor-browser-bin

### Purpose:

Tor Browser is a free and open-source web browser that allows users to browse the internet anonymously and securely. It is developed by the Tor Project, a non-profit organization that aims to promote online privacy and freedom.

### Benefits:

Tor Browser is a powerful tool for maintaining online privacy and security. By using Tor Browser, users can browse the internet anonymously and securely, protecting themselves from online surveillance and tracking.

### Copyright:

GPL

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

Currently only available through [torbrowser-launcher](https://archlinux.org/packages/extra/any/torbrowser-launcher/)

**Comment by xiota** [comment] 2024-05-27 20:23
Basically a duplicate of `extra/torbrowser-launcher`.

**Comment by xiota** [comment] 2024-05-28 17:37
I don't think `torbrowser-launcher` is the same as "Tor Launcher" in the press releases.

`torbrowser-launcher --settings` to change mirror or set to download through tor.

**Comment by Technetium1** [comment] 2024-05-29 13:24
After collecting the opinions of some users, it seems right to add this package. **It is different from the launcher**, but is still worth adding independently.

**Closed** 2024-05-29 13:25 UTC
Labels: request:new-pkg, priority:medium

**Comment by dandare1980** [comment] 2024-05-29 18:46
Excellent news, thank you.

The only way  [torbrowser-launcher](https://archlinux.org/packages/extra/any/torbrowser-launcher/) will work with my ISP is to use it with a VPN.

Selecting alternative mirrors in Tor Browser Launcher Settings had no effect as they also appear to be blocked.

This package will help many in a similar situation.
