### ISSUE TITLE
compiz-git and changed pkgver

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#1434] opened 2022-05-14 10:56 UTC
### Package name

`compiz-git`

### Latest build

`0.9.14.1.r0.g8b3fdfd7c-1`

### Latest version available

`0.9.14.1.r0.g8b3fdfd7c-1.1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Why does the version of `compiz-git` have pkgver changed from 0.9.14.1.r0.g8b3fdfd7c-1 to 0.9.14.1.r0.g8b3fdfd7c-1.1 Today I built` compiz-git` out of curiosity and it's still version 0.9.14.1.r0.g8b3fdfd7c -1, I would very much like to ask you not to arbitrarily change pkgver into the chaotic-aur repo because after updating `protobuf` it is necessary to rebuild` compiz-git` and when it is rebuilt to the previous version, the chaotic-aur repo will want to update it.

**Comment by dr460nf1r3** [comment] 2022-05-14 11:09
This is in fact caused by our bumping system which does exactly what you are requesting. See that line of our [interfere repo](https://github.com/chaotic-aur/interfere/blob/master/PKGREL_BUMPS#L33) for reference. Since the bump once increments the version by 0.1 instead of 1, changes to pkgrel that happen in AUR still apply to all packages.

**Comment by dr460nf1r3** [comment] 2022-05-14 11:11
Fixed in https://github.com/chaotic-aur/interfere/commit/f305b2000316c56774aafe1c649fbb4c3531ced0

**Closed by dr460nf1r3** 2022-05-14 11:11 UTC
Labels: request:rebuild-pkg, priority:high

**Comment by robson-66** [comment] 2022-05-14 11:43
I did not mean to update `compiz-git` to version `0.9.14.1.r0.g8b3fdfd7c-1.2` but to revert to the version that is in AUR which is `0.9.14.1.r0.g8b3fdfd7c-1`

**Comment by dr460nf1r3** [comment] 2022-05-14 11:44
As I said, that is not going to happen for the reason outlined in my first comment.
