### ISSUE TITLE
jitsi package request

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#362] opened 2021-01-14 15:29 UTC
https://aur.archlinux.org/packages/jitsi-meet-desktop-bin/
I have searched on the repos and it has not appeared, only "jitsi" package was there. 

Regards

**Comment by dr460nf1r3** [comment] 2021-01-14 15:56
Duplicate of #361

**Closed by dr460nf1r3** 2021-01-14 15:56 UTC

**Comment by userofryzen** [comment] 2021-01-14 21:53
> Duplicate of #361

Thanks for these packages!  :+1:
