### ISSUE TITLE
[Outdated] Nyrna

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#997] opened 2021-10-18 09:07 UTC
## 👴 For reporting outdated packages

- (If available) Link to latest build: [Here](https://builds.garudalinux.org/repos/chaotic-aur/logs/nyrna.log) (it failed)

- Package name: `nyrna`

- Latest build: `1.3-1`

- Latest version available: `2.2.0-2`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

**Comment by dr460nf1r3** [comment] 2021-10-19 07:01
Its obviously caused by permissions. Recommendations are either adding write permissions to /opt/flutter or adding the current user to `flutterusers` group, which I tried here https://github.com/chaotic-aur/interfere/commit/e52c887090de3c43fd1bd5b4317c0794562077e7. Adding to the group however causes the build to fail without error message and I suspect its needed for successful compilation @PedroHLC

**Comment by Technetium1** [comment] 2022-02-28 20:01
I'm not sure if this is helpful, but someone has [commented](https://aur.archlinux.org/packages/nyrna#comment-853803) on the package:

> Radeox commented on [2022-02-26 13:42 (UTC)](https://aur.archlinux.org/packages/nyrna#comment-853803)
Hey @quasigod, in my setup opt/flutter is owned by my user. I think it's a manual operation you have to do after installing flutter. Try doing a chown -R USER:USER /opt/flutter where USER should be your username :D

**Comment by zany130** [comment] 2022-06-04 21:22
it seems nyrna is no longer in the repos not sure if this is intended. (going through my list of foreign packages to see what may have been removed in the cleanup) fwiw I'm able to build the package

**Comment by dr460nf1r3** [comment] 2022-06-04 21:31
We had a repo cleanup and haven't been able to build it since. The directory permissions and pre-built setup flutter requires doesn't play nice with our toolbox.

**Comment by Technetium1** [comment] 2022-06-05 16:09
There's a new comment:
https://aur.archlinux.org/packages/nyrna#comment-859058

**Comment by zany130** [comment] 2022-11-04 23:34
seems to be out of date again

```
paru nyrna
2 aur/nyrna 2.6.0-1 [+5 ~0.03] [Installed: 2.4.1-1]
    Suspend games and applications at any time and resume whenever you wish
1 chaotic-aur/nyrna 2.4.1-1 [9.40MiB 23.11MiB] [Installed]
    Suspend games and applications at any time and resume whenever you wish
 ```

**Comment by Technetium1** [comment] 2022-11-05 02:11
@dr460nf1r3 seems the interfere broke: https://github.com/chaotic-aur/interfere/tree/master/nyrna
[nyrna.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nyrna.log)

**Comment by dr460nf1r3** [comment] 2022-11-05 11:32
They did change the prepare() function. Fixed in https://github.com/chaotic-aur/interfere/commit/38eae3d378aa1dd4ffbbef25b1502dbd6589821f!

**Closed by dr460nf1r3** 2022-11-05 11:32 UTC
Labels: request:rebuild-pkg, interfere required
