### ISSUE TITLE
[Request] armcord-bin

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2595] opened 2023-06-23 10:55 UTC
### Package:

[armcord-bin](https://aur.archlinux.org/packages/armcord-bin)

### Purpose:

ArmCord is a "privacy" version of Discord. It removes Discord telemetry in order that users can be safer from the privacy point of view.

### Benefits:

No telemetry by Discord. Furthermore, unlike -git version (that currently could have issues on Wayland), the binary package is more stable.

### Copyright:

OSL

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment] 2023-06-27 22:28
> Unique request?
>
> Yes

Duplicate of #2404, by the same author.  Rejected because of excessively large file size.  90MB (bin) vs 1.3MB (git).  This has not changed.

In the future, please write a comment on the old request rather than open a new one.

**Closed** 2023-06-28 07:04 UTC
Labels: invalid:duplicate, priority:low
