### ISSUE TITLE
[Request] yacreader

### ISSUE THREAD

**Issue by kouider01** [chaotic-aur/packages#2197] opened 2022-12-23 18:16 UTC
### Link to the package base(s) in the AUR

[yacreader](https://aur.archlinux.org/packages/yacreader) 

### Utility this package has for you

one of the best free (GPL) comics readers available on the internet, it has some unique features that separate it from the rest.

* easy library management capabilities.
* support for many document formats
* automatic generation of covers 
* automated import of tags from comicvine (this is the most unique, most important feature of this manager)
 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by FabioLolix** [comment] 2022-12-30 13:23
Yacreader needs AUR pkgbuilds `libunarr` and `libpdfium-nojs`, `libpdfium-nojs` need to be rebuilded for every `icu` major version

**Comment by dr460nf1r3** [comment] 2022-12-30 16:49
Thanks for the heads up!

**Comment by Technetium1** [comment] 2023-01-04 18:41
This is a duplicate of chaotic-aur/graveyard#711

**Closed by Technetium1** 2023-01-04 18:41 UTC
Labels: invalid:duplicate, request:new-pkg
