### ISSUE TITLE
[Rebuild] cemu-git

### ISSUE THREAD

**Issue by danielah05** [chaotic-aur/packages#3315] opened 2024-09-12 21:05 UTC
### Packages:

https://aur.archlinux.org/packages/cemu-git

### Latest chaotic version

2.2.r0.g1a4d9660-1

### Reason for rebuild

dependency resolve error:
warning: cannot resolve "libfmt.so=10-64", a dependency of "cemu-git"

**Comment by Technetium1** [comment] 2024-09-12 21:34
Maybe broken due to https://github.com/fmtlib/fmt being at v11 now https://gitlab.archlinux.org/archlinux/packaging/packages/fmt/-/commits/main
while `fmt9` is required at https://github.com/cemu-project/Cemu/blob/1a4d9660e756f52a01589add71df619361543a2f/CMakeLists.txt#L157
Build log: [cemu-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/cemu-git.log)

**Comment by SteavenGamerYT** [comment] 2024-09-13 06:33
build fmt9 and make cemu use it somehow?

**Comment by xiota** [comment] 2024-09-13 08:01
An issue was opened upstream.  Will wait a little while before trying to interfere.

**Comment by Technetium1** [comment] 2024-09-13 16:33
Upstream issue 1338: `only works with libfmt 10`, not linking directly.

**Comment by xiota** [comment] 2024-09-16 00:17
AUR maintainer added dep on `aur/fmt10`, but will not add `fmt10` to chaotic-aur (yet).  Will give upstream projects little more time to update before adding interferes.

The problem is legacy packages don't fix the problem for all affected packages, the interferes are potentially complicated,  and changes will eventually have to be rolled back when upstream updates.

**Comment by xiota** [comment] 2024-09-17 04:09
I was looking at the wrong package earlier.  `aur/cemu` is the one that added `fmt10`.

Will switch `cemu-git` and a few other packages to custom packages because they already have extensive interferes with multiple fixups.  Closing because test rebuild of `cemu-git` was successful and package is available in repo.

**Closed by xiota** 2024-09-17 04:09 UTC
Labels: request:rebuild-pkg, interfere required, priority:medium, bug:misc
