### ISSUE TITLE
[Request] pure-maps-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1878] opened 2022-09-04 21:58 UTC
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/pure-maps-git

### Utility this package has for you

An application for Linux to display vector and raster maps, places, routes, etc.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment] 2022-09-24 02:02
Currently flagged out of date, waiting to add since there are a lot of new deps that might change.

**Comment by Technetium1** [comment] 2022-12-10 09:29
It's been 7 months with no update. I assume this package has died. Please mention me here in the future if it's ever updated :(

**Comment by tio-trom** [comment] 2023-11-24 21:33
What about the git version? https://aur.archlinux.org/packages/pure-maps-git - seems to be maintained

**Comment by Technetium1** [comment] 2023-11-24 22:24
> First Submitted: 2023-10-31 14:59 (EDT)

Didn't see this one.

**Comment by xiota** [comment] 2023-11-24 23:30
`aur/pure-maps-git` package needs to review/revision.

* Unusual version format.
* Possibly unnecessary depends.
    - The deletion request against `python-geomag-todd-dembrey-git` says it's not really needed for `pure-maps`.
* I prefer the url of git packages to point to the git project page.

**Comment by xiota** [comment] 2023-11-28 10:50
Maintainer disowned, and I adopted.  Found that this package and most of its dependencies were broken and abandoned.  They are now working, and `pure-maps-git` is in the repo for testing.

@tio-trom Please test and let me know if it is working.  It has not yet been added to the package lists, so don't close this issue unless you no longer want the package added.

**Comment by tio-trom** [comment] 2023-11-28 12:10
Thank you!

It worked to install but not to start it: `pure-maps: error while loading shared libraries: libabsl_hash.so.2206.0.0: cannot open shared object file: No such file or directory` - might be because i am using a manjaro spin and some libraries may need to be more up to date but am not sure...

**Comment by xiota** [comment] 2023-11-28 12:33
> `libabsl_hash.so.2206.0.0`

Install `abseil-cpp`.  I'll update the depends.

**Comment by tio-trom** [comment] 2023-11-28 13:12
I do have that installed already... 20230802.1-1 - perhaps is older than the pure-maps needs it to be.

**Comment by xiota** [comment] 2023-11-28 20:23
The problem is the version of the package you have is too new.  I will try rebuilding after I figure out what version the build server has installed.

**Comment by xiota** [comment] 2023-12-03 01:29
Rejected because insufficient justification for maintenance effort.

**Closed by xiota** 2023-12-03 01:29 UTC
Labels: request:new-pkg, priority:low
