### ISSUE TITLE
[Request] samba-support

### ISSUE THREAD

**Issue by ghost** [chaotic-aur/packages#2912] opened 2023-11-17 18:34 UTC
### Package:

https://aur.archlinux.org/packages/samba-support

### Purpose:

Make configuring samba easier

### Copyright:

GPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

No

### Banned package?

No

**Comment by Technetium1** [comment] 2023-11-17 23:10
We won't be able to provide the optdep [system-config-samba](https://aur.archlinux.org/packages/system-config-samba) since it depends on python2

**Comment by trellotest07** [comment] 2023-11-18 08:31
samba-support does the job without system-config-samba, hence it is a optdep. Personally, I don't use nor install it.

**Comment by xiota** [comment] 2023-11-18 20:36
I don't see the point of providing this package.  It's mostly just a config file and the package is improperly constructed.

**Comment by trellotest07** [comment] 2023-11-18 20:47
@xiota It's easier to install the package to get samba set, than to deal with samba configuration files that tend to be complicated.

**Comment by xiota** [comment] 2023-11-18 20:53
You can copy the config or build it locally.

**Comment by adilno9** [comment] 2023-11-25 06:04
I found this package randomly when I was looking for a gui/way to configure Samba, and it worked as intended. I think it will be fine to add it to Chaotic.
 But the maintainer of the AUR package won't make changes suggested by @xiota as it seems. So will this issue be resolved or left open?

**Comment by xiota** [comment] 2023-11-25 07:14
If it's solely up to me, I wouldn't add it.

In addition to the depends issue, the install script creates and adds all users to a new group.  Then on uninstall, deletes the group.  Considering the nature of the related packages, this will leave files owned by an unassigned group id.

**Comment by dr460nf1r3** [comment] 2023-11-25 14:49
We have the same package under our control at Garuda Linux. In fact, this package was derived from it (see [here](https://gitlab.com/garuda-linux/pkgbuilds/-/tree/main/samba-support?ref_type=heads)) - we might fix it and take this one as source instead?

**Comment by xiota** [comment] 2023-11-25 18:48
If request is from a deleted account, maybe shouldn't add it.  But Garuda version should be fixed.

**Comment by dr460nf1r3** [comment] 2023-12-11 18:05
I personally don't use samba so it would be great if someone could test the new PKGBUILDs for functionality. Also asked for feedback in the Garuda forum.

**Comment by Technetium1** [comment] 2024-05-25 07:28
@dr460nf1r3 did you get a meaningful followup for this?

**Comment by dr460nf1r3** [comment] 2024-05-25 07:29
Not at all :( shall we push it nevertheless?

**Closed** 2024-05-25 07:32 UTC
Labels: request:new-pkg, rejected:nature

**Comment by xiota** [comment] 2024-05-25 07:43
I think it should be rejected for poor packaging.  Maintainer refused to make any changes.

**Comment by xiota** [comment] 2024-05-25 08:03
I was working on an alternate, but got distracted... may finish it someday.
