### ISSUE TITLE
[Request] gnome-browser-connector

### ISSUE THREAD

**Issue by Evan-aja** [chaotic-aur/packages#1634] opened 2022-08-09 03:43 UTC
### Link to the package(s) in the AUR

[gnome-broser-connector](https://aur.archlinux.org/packages/gnome-browser-connector)

### Utility this package has for you

The package `chrome-gnome-shell` should be replaced with this new package since the former, although operational, has been replaced by Gnome

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment] 2022-08-09 05:07
Accidental duplicate of #1633

**Closed by Technetium1** 2022-08-09 05:07 UTC
Labels: invalid:duplicate, request:new-pkg
