### ISSUE TITLE
[Issue] Kwin-git and other plasma-git, KDE-applications-git and kf5-git packages are outdated

### ISSUE THREAD

**Issue by rkunschke** [chaotic-aur/packages#662] opened 2021-06-10 10:56 UTC
Most of the packages out of these groups received no updates since the 30.05. 
I don't really know how the chaotic AUR works but shouldn't they get new builds when there are new commits in the git-repository?

**Comment by dr460nf1r3** [comment] 2021-06-10 11:54
You are right, actually builds happen daily for those. There must be something interfering, Ill check that. Thanks for reporting :)

**Comment by dr460nf1r3** [comment] 2021-06-12 15:46
Alright, as @IslandC0der fixed extra-cmake-modules compiling works as expected again. Will take some time to get every package up to date now 😁

**Comment by IslandC0der** [comment] 2021-06-12 17:36
Hmm that's odd, the patch should only make it so it doesn't generate that `__init__.py` file, didn't expect it to fix any compiling errors 😂

**Comment by dr460nf1r3** [comment] 2021-06-12 17:39
Well it wasnt actually the compiling process rather than the phase of installing dependencies which failed due to the file conflict 😋 I just call the whole thing "compiling" even though it involves different processes :D

**Comment by rkunschke** [comment] 2021-06-13 12:36
Lots of packages are up-to date now :) some are not
I build the remaining ones via AUR but was'nt able to build four of them:
https://aur.archlinux.org/packages/kauth-git/
https://aur.archlinux.org/packages/kconfigwidgets-git
https://aur.archlinux.org/packages/kdsoap-git/
https://aur.archlinux.org/packages/kdsoap-ws-discovery-client-git/
All four are maintained by @IslandC0der 
Can you check these? I think if there are fixed, everything will be up-to-date again.

**Comment by dr460nf1r3** [comment] 2021-06-14 07:40
So, kconfigwidgets-git, kdenlive-git, kdsoap-git need to be fixed - logs can be found [here](https://builds.garudalinux.org/repos/chaotic-aur/logs/) :)

**Comment by IslandC0der** [comment] 2021-06-17 08:02
Alright thank you @dr460nf1r3, I'll see if I can get it fixed this weekend :)

**Comment by IslandC0der** [comment] 2021-07-17 00:26
Hmm, looks like the issue with `kconfigwidgets-git` and `kdenlive-git` actually stems for `kcodecs-git`
Time to go fix that! :)
I think the other ones are fine now, judging by the logs and build dates; but are there any still bugging you, @rkunschke?

**Comment by IslandC0der** [comment] 2021-07-18 14:48
Hopefully [this](https://github.com/chaotic-aur/interfere/commit/602c4bf35a02061716fa686c2ecb8acd95d40ece) will fix it!

**Comment by dr460nf1r3** [comment] 2021-07-18 15:19
They are compiling now :) Just the version of `kcodecs-git` is pretty off, 5.71 days are long gone :D

**Comment by IslandC0der** [comment] 2021-07-18 18:13
Oops, forgot to add the fixed `pkgver()` to interfere

**Comment by rkunschke** [comment] 2021-07-19 13:04
Seems like everything is updated now :)
But starting kmail results in this error:
kmail: symbol lookup error: /usr/lib/libkmailprivate.so.5: undefined symbol: _ZN16KShortcutsDialog10showDialogEP17KActionCollectionN16KShortcutsEditor15LetterShortcutsEP7QWidget
Any ideas about that? Everything works normal without these packages.
I installed these groups: plasma-git kde-applications-git kf5-git kde-git

**Comment by dr460nf1r3** [comment] 2021-07-19 13:28
Guess we can close this issue then as the original problem is resolved. No idea what that error could be though 👀

**Closed by dr460nf1r3** 2021-07-19 13:28 UTC
Labels: bug, pkg rebuild

**Comment by IslandC0der** [comment] 2021-07-19 19:41
Apparently there was no `kmail-git`... That looks like it was caused by using the stable version of `kmail` with `-git` libraries.
But I've just added it now, could you please check if it solves that issue when it becomes available on your mirror?

**Comment by rkunschke** [comment] 2021-07-20 18:15
okay thank you. I will try when kmail-git becomes available.

**Comment by dr460nf1r3** [comment] 2021-07-20 20:07
`error: target not found: kdepim-runtime-git
error: target not found: kmail-account-wizard-git
error: target not found: akonadi-import-wizard-git
error: target not found: mbox-importer-git
error: target not found: pim-data-exporter-git
error: target not found: pim-sieve-editor-git`
☹️

**Comment by IslandC0der** [comment] 2021-07-20 21:07
I added them too, they have to be built first
But shouldn't the dependencies be compiled first automatically, in a given routine? Otherwise, that's bound to cause problems 👀
