### ISSUE TITLE
[Request] python-fakewebcam

### ISSUE THREAD

**Issue by bphd** [chaotic-aur/packages#2738] opened 2023-08-20 19:25 UTC
## Package: python-fakewebcam

**Package:** [python-fakewebcam](https://aur.archlinux.org/packages/python-fakewebcam)
**Purpose:** python-fakewebcam is a Python library that allows users to create virtual webcams and stream images or videos to applications as if they were real cameras.
**Benefits:** This package enables creative applications, such as virtual backgrounds, visual effects, and custom overlays in video conferencing and streaming software.
**Building:** To build the python-fakewebcam package, follow these steps in a clean chroot:
```shell
git clone https://aur.archlinux.org/python-fakewebcam.git
cd python-fakewebcam
makepkg -si
```
**Copyright:** GPL3 - [GNU General Public License v3](https://www.gnu.org/licenses/gpl-3.0.en.html)
**Expected Interest:** Moderate interest among users interested in enhancing video conferencing and streaming experiences.
**Already available?** Available on AUR but not on Chaotic AUR.
**Unique request?** Yes, this request is unique and not available on Chaotic AUR.
**Banned package?** Not a banned package.
**More information:** python-fakewebcam empowers users to create virtual webcams, allowing for innovative and dynamic visual content in video conferencing and streaming applications.

**Comment by xiota** [comment] 2023-08-20 21:35
`python-fakewebcam-git` appears to be a duplicate of `python-pyfakewebcam-git`.  Deletion request pending.

`python-pyfakewebcam-git` needs to be updated to a new source repository.

@bphd Please fix issues with your requests.
1. Use the actual name of the package in the title, not "packagename"
2. Do not link to the generic license for standard named licenses.
3. Are you actually building the packages in clean chroot or just pasting the commands into the request?  If you are not actually building the packages, do not fill in that section.

**Comment by xiota** [comment] 2023-08-30 04:20
Rejecting for poor maintainership.  All related packages (`python-fakewebcam`, `python-pyfakewebcam`, `python-pyfakewebcam-git`) have unresolved issues and unresponsive maintainers.

This request can be reconsidered if `python-pyfakewebcam` or `python-pyfakewebcam-git` are fixed and updated.

**Closed by xiota** 2023-08-30 04:20 UTC
Labels: request:new-pkg, waiting:upstream-fix, rejected:nature

**Comment by Technetium1** [comment] 2023-08-30 17:06
Upstream died. Use `v4l2loopback` instead.

**Comment by xiota** [comment] 2023-08-30 17:54
```
$ pacman -Ss v4l2loopback
extra/v4l2loopback-dkms 0.12.7-2
    v4l2-loopback device – module sources
extra/v4l2loopback-utils 0.12.7-2
    v4l2-loopback device – utilities only
chaotic-aur/v4l2loopback-dc-dkms 1:2.0.0-1
    A tool for using your android device as a wireless/usb webcam
```
