### ISSUE TITLE
[Request]  xdg-desktop-portal-hyprland-git

### ISSUE THREAD

**Issue by romanstingler** [chaotic-aur/packages#2813] opened 2023-09-24 21:05 UTC
### Package:

https://aur.archlinux.org/packages/xdg-desktop-portal-hyprland-git

### Purpose:

An [XDG Desktop Portal](https://github.com/flatpak/xdg-desktop-portal) backend for Hyprland.

### Benefits:

This is important for screen sharing and other stuff with Hyprland WM

### Building:

current PKGBUILD needs additionally 
`sdbus-cpp` as build dependency. 

### Copyright:

custom:MIT 

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment] 2023-10-03 22:42
Still flagged out of date

**Comment by xiota** [comment] 2024-01-08 23:35
This was already added in 81edca947c93bc3c94cf9734e885ac42cf17a558, but the package is very broken.  I'm switching it over to a hybrid interfere.

* Wrong `pkgver` format.  Should be `#.r#.g#`.
* `license` should be `MIT`.  `custom:` prefix is no needed.  See [PKGBUILD#license](https://wiki.archlinux.org/title/PKGBUILD#license).
* `provides` should be versioned, `"$_pkgname=${_pkgver%.r*}"`.
* optdeps may not all be needed, optdeps generally pointless
* `options` not needed.  Bad practice to disregard user makeflags and buildflags.
* `pkgver()` is overly complicated and not working as intended.  (Doesn't matter that it's from the wiki.  That piped code is broken and shouldn't be used.)
* git submodules should be listed in `source` and initialized in `prepare()`.  See [VCS package guidelines](https://wiki.archlinux.org/title/VCS_package_guidelines#Git_submodules).
    * The submodules are small and may not be worth the complicated setup.  By convention, they should still be initialized in `prepare()`.
    * While there are advantages to initializing in `build()` instead of `prepare()`, the default behavior should follow standard conventions.
* `cmake` options need to be cleaned up/organized.
* Additional options for `cmake --build build` are unnecessary.
* `-j nproc...` should not be used.  Users should set these up themselves in [`makepkg.conf`](https://wiki.archlinux.org/title/Makepkg#Parallel_compilation).
* `cmake --install` is missing `DESTDIR`.
* License file is installed to wrong location.  Should be `"$pkgdir/usr/share/licenses/$pkgname"` (not `$_pkgname`).

**Comment by xiota** [comment] 2024-03-18 22:07
@SteavenGamerYT What needs to be fixed?

**Comment by SteavenGamerYT** [comment] 2024-03-19 02:37
yay -S xdg-desktop-portal-hyprland-git
Sync Explicit (1): xdg-desktop-portal-hyprland-git-1.3.1.r14.g2d2fb547-1
warning: xdg-desktop-portal-hyprland-git-1.3.1.r14.g2d2fb547-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
:: hyprlang-0.4.1-1 and hyprlang-git-0.5.0.r0.a685493-1 are in conflict. Remove hyprlang-git? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing hyprlang-git breaks dependency 'hyprlang>=0.4.2' required by hyprcursor-git
 -> error installing repo packages

**Comment by SteavenGamerYT** [comment] 2024-03-19 02:37
i have currently installed it just fine from aur

**Comment by xiota** [comment] 2024-03-19 08:06
The AUR package has fixed most of the defects.  The following remain:

* Does not use git submodules
* Extraneous arguments in cmake build command
* Wrong license path
* Provides are not versioned

Additionally, `hyprlang` and `hyprlang-git` are no longer compatible with each other.  The interfere now needs to be kept to select the -git packages.

**Closed by xiota** 2024-03-19 08:05 UTC
Labels: request:new-pkg, interfere required, priority:low, bug:PKGBUILD
