### ISSUE TITLE
qtcreator-prerelease [Request] 

### ISSUE THREAD

**Issue by dmaliog** [chaotic-aur/packages#3225] opened 2024-07-17 19:04 UTC
### Package:

https://aur.archlinux.org/packages/qtcreator-prerelease

### Purpose:

Creating applications using QT

### Benefits:

Always the latest version

### Copyright:

GPL

### Expected Interest:

Most

### Already available?

No

### Unique request?

No

### Banned package?

No

### More information:

Thanks in advance

**Comment by Technetium1** [comment] 2024-07-18 22:11
Build fails: [qtcreator-prerelease.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/qtcreator-prerelease.log)

**Comment by dmaliog** [comment] 2024-07-20 00:47
Perhaps you could try using https://github.com/qt-creator/qt-creator

**Comment by xiota** [comment] 2024-07-20 01:59
The PKGBUILD needs to be rewritten.  Should be synced with `extra/qtcreator`.

**Comment by dmaliog** [comment] 2024-07-20 19:38
I still hope that you can do something, because this is the only way out of the installation.  The old version no longer runs due to an error, so you have to use the latest one and wait for the build.  :)

**Comment by xiota** [comment] 2024-07-20 19:59
>  The old version no longer runs due to an error

That's the type of info that's helpful in the request (benefits).  Can you provide more info about the error?  What is the error message, and when does it occur?  Could it be fixed by the package maintainer, or would it require a new upstream release?

**Comment by dmaliog** [comment] 2024-07-21 05:11
> > The old version no longer runs due to an error
> 
> That's the type of info that's helpful in the request (benefits). Can you provide more info about the error? What is the error message, and when does it occur? Could it be fixed by the package maintainer, or would it require a new upstream release?

Most likely this is due to the old version of qtcreator (13.0.2-5), in the new one taken from (https://aur.archlinux.org/packages/qtcreator-prerelease) everything works (13.0.84)
 The error is as follows when enabling qtcreator - qtcreator: symbol lookup error: /usr/bin/../lib64/qtcreator/libUtils.so.13: undefined symbol: _ZN19QAbstractFileEngine11setFileTimeERK9QDateTimeNS_8FileTimeE, version Qt_6.7_PRIVATE_API

**Comment by dmaliog** [comment] 2024-07-21 05:14
Because of this, there was a need for a new version that is already compiled

**Comment by xiota** [comment] 2024-07-21 05:19
That is the type of error that typically occurs when a package requires rebuild.  I will test and, if relevant, open an issue with Arch to request rebuild.  Assuming rebuild resolves the problem, would the prerelease package still be needed?

**Comment by dmaliog** [comment] 2024-07-21 05:55
> That is the type of error that typically occurs when a package requires rebuild.  I will test and, if relevant, open an issue with Arch to request rebuild.  Assuming rebuild resolves the problem, would the prerelease package still be needed?

Most likely, the need for this will not disappear, I would like to have an airbag if something is wrong with the main one

**Comment by xiota** [comment] 2024-07-21 06:09
Cannot reproduce your issue.  What distro are you using?  Is it fully updated? (`sudo pacman -Syuu`)

![qtcreator](https://github.com/user-attachments/assets/b17669aa-ed61-472f-9519-a932ae23205f)

**Comment by dmaliog** [comment] 2024-07-21 20:28
> Cannot reproduce your issue. What distro are you using? Is it fully updated? (`sudo pacman -Syuu`)
> 
> ![qtcreator](https://private-user-images.githubusercontent.com/8353098/350740656-b17669aa-ed61-472f-9519-a932ae23205f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTI2MzgsIm5iZiI6MTcyMTU5MjMzOCwicGF0aCI6Ii84MzUzMDk4LzM1MDc0MDY1Ni1iMTc2NjlhYS1lZDYxLTQ3MmYtOTUxOS1hOTMyYWUyMzIwNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjFUMjAwNTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjliOTMxNmIzZTUyZWUzNTY0NmI4Zjc0OGNhMTRhNGZmZjc0YTYwMzhlNjVkZGQ1MDkyYjQ3MGY1YWE2ZjllNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4Kp_KwdNEmavX2fGXAT_3--AoA3kbtrMqK_6OVcN6lY)


https://github.com/user-attachments/assets/28e6b36e-10bd-4e61-92cf-eef8da07f0b8

**Comment by dmaliog** [comment] 2024-07-21 20:30
> Cannot reproduce your issue. What distro are you using? Is it fully updated? (`sudo pacman -Syuu`)
> 
> ![qtcreator](https://private-user-images.githubusercontent.com/8353098/350740656-b17669aa-ed61-472f-9519-a932ae23205f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTQwNzgsIm5iZiI6MTcyMTU5Mzc3OCwicGF0aCI6Ii84MzUzMDk4LzM1MDc0MDY1Ni1iMTc2NjlhYS1lZDYxLTQ3MmYtOTUxOS1hOTMyYWUyMzIwNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjFUMjAyOTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjUwMDgzNmExYzgwZmE0NmEwNmM3ZGJkODVmY2MwMmRmY2FlYzM2YTRmNGY5NGM4ZmZlMTVmYWM1N2Q1Mjc0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KXXHPVLWe8ZidUMFOeqZyNfCCbNeCycjk5AVZpPLiHY)


https://github.com/user-attachments/assets/78eb53f3-4c94-4091-ae3a-e893275947a5

**Comment by dmaliog** [comment] 2024-07-21 20:37
> Cannot reproduce your issue. What distro are you using? Is it fully updated? (`sudo pacman -Syuu`)
> 
> ![qtcreator](https://private-user-images.githubusercontent.com/8353098/350740656-b17669aa-ed61-472f-9519-a932ae23205f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTQxNjAsIm5iZiI6MTcyMTU5Mzg2MCwicGF0aCI6Ii84MzUzMDk4LzM1MDc0MDY1Ni1iMTc2NjlhYS1lZDYxLTQ3MmYtOTUxOS1hOTMyYWUyMzIwNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjFUMjAzMTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQyNmVjMWFjODZkMmIxODcwYzE2NTVmYmY3MzdjZmI0MTkzY2IzMDI3OTBjMjExNWFkN2Y5ZGJiNWJjNWY1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T1KIEWa-D4JY5NLM6rJvS-gVnGcIQDWgljgt3wlgJaA)

Yes everything is updated
https://www.veed.io/view/61645757-ad00-43fa-ac3a-82a5ec5e4afe?panel=share

**Comment by xiota** [comment] 2024-07-21 23:16
Rejecting this request.  So far, I have found seven issues with the prerelease package, a couple making it unbuildable in clean chroot.  Also, the purpose of using it as backup is not worth devoting resources to build and store it.

The prerelease package built on chaotic-aur servers would have a good chance of having the same problem on your system as the `extra` package because it would have been built with standard Arch packages, while packages built on your system are specific to your system.

Something is probably misconfigured on your system because the path in your error (`/usr/bin/../lib64/qtcreator/libUtils.so.13`) is not a standard Arch path.

```
$ pacman -Fl qtcreator | grep libUtils.so
qtcreator usr/lib/qtcreator/libUtils.so.13
qtcreator usr/lib/qtcreator/libUtils.so.13.0.2
```

**Closed by xiota** 2024-07-21 23:16 UTC
Labels: request:new-pkg, reject:too-hard-for-us, bug:PKGBUILD
