### ISSUE TITLE
[Maintenance] Repo cleanup (old/dropped/broken packages) 🔧

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2358] opened 2023-04-03 08:57 UTC
There are 200-some missing packages.  I'll prepare some PRs to try to remove or fix them in stages.  Since my list contains some false positives, I'll do my best to double check before opening each PR.  Feel free to let me know whether any specific packages should be fixed, definitely removed, or anything else.

**Comment by dr460nf1r3** [comment] 2023-04-03 12:38
It's great you made the list! I'm assuming that most of these are packages that never succeeded building after a full repository rebuild. Looking into the packages build logs sounds like a great idea, before eventually dropping them.

**Comment by xiota** [comment] 2023-04-03 14:13
One package is misnamed, "śimple-mtpfs".  The first letter should be a normal `s` – `simple-mtpfs`.  https://github.com/chaotic-aur/packages/issues/1410

<details><summary>Links to package build logs.</summary>

* [akonadi-import-wizard-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/akonadi-import-wizard-git.log)
* [alacritty-ligatures-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/alacritty-ligatures-git.log)
* [arm-linux-gnueabi-gcc](https://builds.garudalinux.org/repos/chaotic-aur/logs/arm-linux-gnueabi-gcc.log)
* [asusctl-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/asusctl-git.log)
* [ayatana-indicator-power](https://builds.garudalinux.org/repos/chaotic-aur/logs/ayatana-indicator-power.log)
* [bat-cat-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/bat-cat-git.log)
* [blackbox-terminal-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/blackbox-terminal-git.log)
* [blueprint-compiler-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/blueprint-compiler-git.log)
* [c++utilities](https://builds.garudalinux.org/repos/chaotic-aur/logs/c++utilities.log)
* [cachyos-ananicy-rules](https://builds.garudalinux.org/repos/chaotic-aur/logs/cachyos-ananicy-rules.log)
* [canta-theme](https://builds.garudalinux.org/repos/chaotic-aur/logs/canta-theme.log)
* [canta-theme-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/canta-theme-git.log)
* [catppuccin-grub-theme-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/catppuccin-grub-theme-git.log)
* [cmst-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/cmst-git.log)
* [decaf-emu-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/decaf-emu-git.log)
* [doomseeker](https://builds.garudalinux.org/repos/chaotic-aur/logs/doomseeker.log)
* [dxvk-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/dxvk-git.log)
* [elementary-planner](https://builds.garudalinux.org/repos/chaotic-aur/logs/elementary-planner.log)
* [emacs-ng-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/emacs-ng-git.log)
* [epiphany-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/epiphany-git.log)
* [ferdi-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/ferdi-git.log)
* [fluent-reader](https://builds.garudalinux.org/repos/chaotic-aur/logs/fluent-reader.log)
* [fluffychat](https://builds.garudalinux.org/repos/chaotic-aur/logs/fluffychat.log)
* [font-symbola](https://builds.garudalinux.org/repos/chaotic-aur/logs/font-symbola.log)
* [gcc-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/gcc-git.log)
* [gcc10](https://builds.garudalinux.org/repos/chaotic-aur/logs/gcc10.log)
* [generic-monitor-plugin-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/generic-monitor-plugin-git.log)
* [git-bug-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/git-bug-git.log)
* [gitify](https://builds.garudalinux.org/repos/chaotic-aur/logs/gitify.log)
* [glibc-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/glibc-git.log)
* [gnome-contacts-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/gnome-contacts-git.log)
* [gnome-shell-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/gnome-shell-git.log)
* [gnome-text-editor-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/gnome-text-editor-git.log)
* [godot-export-templates-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/godot-export-templates-git.log)
* [granite-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/granite-git.log)
* [grub-themes-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/grub-themes-git.log)
* [gruvbox-material-theme-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/gruvbox-material-theme-git.log)
* [hal-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/hal-git.log)
* [inspircd](https://builds.garudalinux.org/repos/chaotic-aur/logs/inspircd.log)
* [java-p7zip-binding](https://builds.garudalinux.org/repos/chaotic-aur/logs/java-p7zip-binding.log)
* [kde-rounded-corners](https://builds.garudalinux.org/repos/chaotic-aur/logs/kde-rounded-corners.log)
* [kite](https://builds.garudalinux.org/repos/chaotic-aur/logs/kite.log)
* [kotatogram-dev-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/kotatogram-dev-git.log)
* [lariza](https://builds.garudalinux.org/repos/chaotic-aur/logs/lariza.log)
* [lbry-desktop-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/lbry-desktop-git.log)
* [lib32-gupnp](https://builds.garudalinux.org/repos/chaotic-aur/logs/lib32-gupnp.log)
* [lib32-gupnp-igd](https://builds.garudalinux.org/repos/chaotic-aur/logs/lib32-gupnp-igd.log)
* [lib32-libnice](https://builds.garudalinux.org/repos/chaotic-aur/logs/lib32-libnice.log)
* [lib32-mesa-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/lib32-mesa-git.log)
* [libgweather-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/libgweather-git.log)
* [libstdc++5](https://builds.garudalinux.org/repos/chaotic-aur/logs/libstdc++5.log)
* [lightdm-pantheon-greeter-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/lightdm-pantheon-greeter-git.log)
* [linuxtv-dvb-apps](https://builds.garudalinux.org/repos/chaotic-aur/logs/linuxtv-dvb-apps.log)
* [llvm-tkg-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/llvm-tkg-git.log)
* [lollypop-next-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/lollypop-next-git.log)
* [manim](https://builds.garudalinux.org/repos/chaotic-aur/logs/manim.log)
* [maui-shell-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/maui-shell-git.log)
* [mauikit-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/mauikit-git.log)
* [megasync-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/megasync-git.log)
* [melonds-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/melonds-git.log)
* [mesa-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/mesa-git.log)
* [metronome-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/metronome-git.log)
* [mimic](https://builds.garudalinux.org/repos/chaotic-aur/logs/mimic.log)
* [mindustry](https://builds.garudalinux.org/repos/chaotic-aur/logs/mindustry.log)
* [mindustry-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/mindustry-git.log)
* [mpv-vapoursynth-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/mpv-vapoursynth-git.log)
* [mycroft-core](https://builds.garudalinux.org/repos/chaotic-aur/logs/mycroft-core.log)
* [mysql57](https://builds.garudalinux.org/repos/chaotic-aur/logs/mysql57.log)
* [nginx-mainline-mod-auth_pam](https://builds.garudalinux.org/repos/chaotic-aur/logs/nginx-mainline-mod-auth_pam.log)
* [nwg-displays](https://builds.garudalinux.org/repos/chaotic-aur/logs/nwg-displays.log)
* [nwg-icon-picker](https://builds.garudalinux.org/repos/chaotic-aur/logs/nwg-icon-picker.log)
* [nwg-panel](https://builds.garudalinux.org/repos/chaotic-aur/logs/nwg-panel.log)
* [obs-hevc-vaapi-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/obs-hevc-vaapi-git.log)
* [obs-nvfbc](https://builds.garudalinux.org/repos/chaotic-aur/logs/obs-nvfbc.log)
* [obs-rtspserver](https://builds.garudalinux.org/repos/chaotic-aur/logs/obs-rtspserver.log)
* [obs-v4l2sink](https://builds.garudalinux.org/repos/chaotic-aur/logs/obs-v4l2sink.log)
* [omnisharp-roslyn](https://builds.garudalinux.org/repos/chaotic-aur/logs/omnisharp-roslyn.log)
* [openboard-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/openboard-git.log)
* [openlitespeed](https://builds.garudalinux.org/repos/chaotic-aur/logs/openlitespeed.log)
* [openvpn3](https://builds.garudalinux.org/repos/chaotic-aur/logs/openvpn3.log)
* [otter-browser-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/otter-browser-git.log)
* [phosh-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/phosh-git.log)
* [php-cs-fixer](https://builds.garudalinux.org/repos/chaotic-aur/logs/php-cs-fixer.log)
* [plasmatube-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/plasmatube-git.log)
* [play-emu-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/play-emu-git.log)
* [powder-toy-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/powder-toy-git.log)
* [python-dephell-pythons](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-dephell-pythons.log)
* [python-dephell-setuptools](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-dephell-setuptools.log)
* [python-dephell-venvs](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-dephell-venvs.log)
* [python-moderngl-window](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-moderngl-window.log)
* [python-poetry-core-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-poetry-core-git.log)
* [python-poetry-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-poetry-git.log)
* [qlog-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/qlog-git.log)
* [quassel-core-lighter-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/quassel-core-lighter-git.log)
* [rapidyaml-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/rapidyaml-git.log)
* [rofi-lbonn-wayland](https://builds.garudalinux.org/repos/chaotic-aur/logs/rofi-lbonn-wayland.log)
* [salad-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/salad-git.log)
* [scrap_engine-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/scrap_engine-git.log)
* [sddm-config-editor-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/sddm-config-editor-git.log)
* [sddm-theme-astronaut](https://builds.garudalinux.org/repos/chaotic-aur/logs/sddm-theme-astronaut.log)
* [shadowsocks-rust-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/shadowsocks-rust-git.log)
* [steam-rom-manager-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/steam-rom-manager-git.log)
* [steinberg-asio-sdk](https://builds.garudalinux.org/repos/chaotic-aur/logs/steinberg-asio-sdk.log)
* [streamdeck-ui-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/streamdeck-ui-git.log)
* [sushi-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/sushi-git.log)
* [swayfire-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/swayfire-git.log)
* [swift-language-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/swift-language-git.log)
* [telephant-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/telephant-git.log)
* [tfsec](https://builds.garudalinux.org/repos/chaotic-aur/logs/tfsec.log)
* [tilix-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/tilix-git.log)
* [tk-itk](https://builds.garudalinux.org/repos/chaotic-aur/logs/tk-itk.log)
* [tok-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/tok-git.log)
* [ttf-iskpota](https://builds.garudalinux.org/repos/chaotic-aur/logs/ttf-iskpota.log)
* [tuner](https://builds.garudalinux.org/repos/chaotic-aur/logs/tuner.log)
* [unflac](https://builds.garudalinux.org/repos/chaotic-aur/logs/unflac.log)
* [vala-panel-applets-gpl-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/vala-panel-applets-gpl-git.log)
* [vboot-utils](https://builds.garudalinux.org/repos/chaotic-aur/logs/vboot-utils.log)
* [vim-coc-diagnostic-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/vim-coc-diagnostic-git.log)
* [vim-coc-java-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/vim-coc-java-git.log)
* [vim-coc-vimlsp-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/vim-coc-vimlsp-git.log)
* [vte3-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/vte3-git.log)
* [windscribe-bin](https://builds.garudalinux.org/repos/chaotic-aur/logs/windscribe-bin.log)
* [windscribe-cli](https://builds.garudalinux.org/repos/chaotic-aur/logs/windscribe-cli.log)
* [wineasio-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/wineasio-git.log)
* [wxgtk-3.1.5](https://builds.garudalinux.org/repos/chaotic-aur/logs/wxgtk-3.1.5.log)
* [wxgtk-dev](https://builds.garudalinux.org/repos/chaotic-aur/logs/wxgtk-dev.log)
* [xmm7360-pci-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/xmm7360-pci-git.log)
* [yin-yang-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/yin-yang-git.log)
* [yuzu-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/yuzu-git.log)
* [zecwallet-lite](https://builds.garudalinux.org/repos/chaotic-aur/logs/zecwallet-lite.log)
* [zestginx](https://builds.garudalinux.org/repos/chaotic-aur/logs/zestginx.log)
</details>

<details><summary>Packages missing build logs.</summary>

* amdgpu-pro-installer
* android-udev
* aura-fetch-git
* aws-cli-v2-bin
* bear
* binfmt-qemu-static
* caja-pdf-tools-git
* chrome-gnome-shell
* chromium-ublock-origin
* citra-qt-git
* connman-gtk-git
* dmenu-height
* dnf
* dotnet-core-bin
* exe-thumbnailer
* flite1-patched
* freeplane
* gnome-control-center-x11-scaling
* godot-beta-bin
* gst-rtsp-server
* guestfs-tools
* hblock
* ibus-mozc-ut
* itk-snap
* j4-dmenu-desktop
* kms.git
* kooha
* kvantum-theme-layan-git
* kwallet-secrets
* layan-kde-git
* lib32-llvm-git
* lib32-numactl
* libdispatch
* libdnf
* libxft-bgra
* libxnvctrl-390xx
* lightcord-bin
* mangohud-wayland
* masterpdfeditor-libs-included
* mozc-ut-common
* musixmatch-bin
* nerd-fonts-hack
* netflix-git
* nvidia-390xx-settings
* nvidia-utils-keylase
* oomox-qt5-styleplugin-git
* oomox-qt6-styleplugin-git
* opencolorio-qfix
* openh264
* openimageio-qfix
* openshadinglanguage-qfix
* osh
* performance-tweaks
* prjxray-tools-git
* protonvpn-cli-ng
* python-asttokens
* python-crcmod
* python-grpcio-tools
* python-mainimpango
* python-pathlib
* python-python_socks
* python-springcase
* python-torchvision
* quassel-git
* rootactions-servicemenu
* rtl8814au-aircrack-dkms-git
* ruby-coderay
* ruby-method_source
* ruby-pry
* sneedacity-git
* stern
* tabledeps-git.git
* tectonic
* tuxedo-control-center
* vim-coc-dictionary-git
* vim-coc-emoji-git
* vim-coc-syntax-git
* vim-coc-tag-git
* vim-coc-word-git
* vte-ng
* wgcf
* wine-lol-glibc
* woeusb-gui
* wxwidgets-dev-light
</details>

Next steps?

**Comment by xiota** [comment] 2023-04-05 21:02
One of the missing packages is `manim`.  I noticed it is in a section that belongs to @RustemB, but that user has no activity on GitHub since the end of 2021 (corresponding with a geopolitical event in the region).

Should `manim` be dropped or fixed?  Since it's a broken package, there are probably no download stats to gauge interest.

**Comment by FabioLolix** [comment] 2023-04-05 21:04
> binfmt-qemu-static

Is superseeded by qemu-user-static-binfmt https://archlinux.org/packages/extra/x86_64/qemu-user-static-binfmt/ if I recall well

> woeusb-gui

is now woeusbgui 

* https://aur.archlinux.org/packages/woeusbgui
* https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/4BJWOPDJQPHOWHKOSCNGK5ZYZ37BJR3Z/

> dmenu-height

Removed as personal build of dmenu
* https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/KJH6UPBY6SWE54DTVV6N2DOVRLUGWN26/

> chrome-gnome-shell

Now is gnome-browser-connector
* https://aur.archlinux.org/packages/gnome-browser-connector
* https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/GON5H5W3XQEEZCYYFJGK4G2OX2OY53FO/

> sneedacity

Removed from AUR https://lists.archlinux.org/archives/search?mlist=aur-requests%40lists.archlinux.org&q=sneedacity

***

> mauikit-git

Need mauiman-git at the moment

> maui-shell-git

Need other packages

**Comment by dr460nf1r3** [comment] 2023-04-05 21:13
> One of the missing packages is `manim`.  I noticed it is in a section that belongs to @RustemB, but that user has no activity on GitHub since the end of 2021 (corresponding with a geopolitical event in the region).

This has another very sad cause, our fellow co-maintainer collegue passed away during that time. 

> Should `manim` be dropped or fixed?  Since it's a broken package, there are probably no download stats to gauge interest.

I recommend dropping it therefore.

**Comment by xiota** [comment] 2023-04-05 21:22
> This has another very sad cause, our fellow co-maintainer collegue passed away during that time.

That is too bad.

**Comment by Technetium1** [comment] 2023-04-05 21:23
@xiota Unfortunately RustemB passed away Dec 2021 😞…
If `manim` no longer builds, then it's a candidate for removal. This _might_ be simply due to a dependency not being in routine yet, so that should be investigated. It wouldn't be unreasonable to open a new issue for that package alone. You are correct that there are no metrics for downloads due to the time it hasn't been building. If it requires manual intervention I think it definitely should be removed.

---

@FabioLolix Thank you!
- `woeusbgui`: is the old unmaintained version, so it should stay dropped
- `chrome-gnome-shell`: had no downloads in a month, so I think we should probably keep it dropped unless it's requested.
- `mauikit-git`: This is still in AUR and routine, is anything wrong with it?
- `maui-shell-git`: Same as `mauikit-git`, is there a cause for this to be removed?

**Comment by FabioLolix** [comment] 2023-04-05 21:44
> mauikit-git: This is still in AUR and routine, is anything wrong with it?
maui-shell-git: Same as mauikit-git, is there a cause for this to be removed?

Not to be removed, it was indicated that there is a build log about it (and it is failing to build), new dependencies are missing

For mauikit-git:
`error: target not found: mauiman-git`

But seems it can be reverted to mauiman

For mauiman-git:
```
error: target not found: cask-server-git
error: target not found: maui-core-git
error: target not found: mauikit-calendar-git
error: target not found: mauikit-git
error: target not found: mauiman-git
```

**Comment by xiota** [comment] 2023-04-05 21:51
@Technetium1 Sorry about the passing of your colleague.

I took a look at trying to fix `manim`.  It would require adding over half a dozen new dependencies.

**Comment by PedroHLC** [comment] 2023-04-06 16:01
> Could I get usage stats for amdgpu-fan?

41 downloads during the last 30 days. For comparison, our 25th most download package was downloaded, 7847 times.

**Comment by xiota** [comment] 2023-04-06 19:27
> > Could I get usage stats for amdgpu-fan?
>
> 41 downloads during the last 30 days.

Thank you.

> For comparison, our 25th most download package was downloaded, 7847 times.

Now that you've mentioned it... What are the top packages and their stats?

**Comment by xiota** [comment] 2023-04-06 21:07
Some packages have essentially empty logs.  What's going on?  For example, `doomseeker` ([log](https://builds.garudalinux.org/repos/chaotic-aur/logs/doomseeker.log)):
```
Building package "doomseeker"
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 multilib downloading...
 chaotic-aur downloading...
:: Starting full system upgrade...
 there is nothing to do
umount: /var/cache/chaotic/routines/hourly/doomseeker/machine/root/home/main-builder/pkgwork unmounted
umount: /var/cache/chaotic/routines/hourly/doomseeker/machine/root/home/main-builder/.ccache unmounted
umount: /var/cache/chaotic/routines/hourly/doomseeker/machine/root/home/main-builder/pkgsrc unmounted
umount: /var/cache/chaotic/routines/hourly/doomseeker/machine/root/var/cache/pacman/pkg unmounted
umount: /var/cache/chaotic/routines/hourly/doomseeker/machine/root/var/pkgdest unmounted
umount: /var/cache/chaotic/routines/hourly/doomseeker/machine/root (overlay) unmounted

real	0m1.846s
user	0m0.453s
sys	0m0.403s
```

**Comment by dr460nf1r3** [comment] 2023-04-06 21:09
I had this happen a few times in the past, in all cases this indicated a somehow broken PKGBUILD. It might or might not be the case here.

**Comment by Technetium1** [comment] 2023-04-07 04:02
@xiota if it's for _many_ things at once, it can be easier to review when they're separated. When something is initially added or removed there's a human interaction behind it. Given what's required I agree with removing `manim`.
Top 50 last month:
<details>

31941	chaotic-mirrorlist
26753	firedragon
25997	game-devices-udev
24695	sweet-theme-full-git
22657	plymouth-git
22175	garuda-hooks
20190	garuda-common-settings
19949	garuda-migrations
19641	candy-icons-git
17355	fastfetch
16974	garuda-update
14866	ananicy-rules
13661	brave-bin
13191	downgrade
13074	dxvk-mingw-git
12964	libpamac-aur
12948	pamac-aur
12412	beautyline
11708	google-chrome
11616	proton-ge-custom
11485	visual-studio-code-bin
9239	firedragon-extension-plasma-integration
8780	chaotic-keyring
8024	archlinux-appstream-data-pamac
7811	garuda-wallpapers-extra
7797	bottles
7545	zoom
7049	retroarch-autoconfig-udev-git
6271	yay
6224	garuda-icons
6088	garuda-fish-config
5958	printer-support
5878	samba-support
5787	scanner-support
5704	virtualbox-ext-oracle
5635	protontricks-git
5590	mangohud
5504	mangohud-common
5481	vkbasalt
5120	libinput-gestures
5079	librewolf
5071	garuda-system-maintenance
5040	pipewire-support
4959	steamtinkerlaunch
4842	garuda-dr460nized
4694	spotify
4667	garuda-setup-assistant
4618	lib32-vkbasalt
4561	onlyoffice-bin
4193	heroic-games-launcher-bin
</details>

**Comment by xiota** [comment] 2023-04-07 15:10
The [build log](https://builds.garudalinux.org/repos/chaotic-aur/logs/decaf-emu-git.log) for `decaf-emu-git` has this error:
```
==> ERROR: /home/main-builder/pkgsrc/cnl is not a clone of https://github.com/johnmcfarlane/cnl
    Aborting...
```
The package cache needs to be cleared because the submodules were recently fixed.

**Comment by dr460nf1r3** [comment] 2023-04-07 15:53
Sources should be cleaned and the package built successfully.

**Comment by xiota** [comment] 2023-04-07 17:05
`tilix-git` is using a PKGBUILD from [chaotic-aur/pkgbuild-tilix-git(https://github.com/chaotic-aur/pkgbuild-tilix-git).  Looks like it was created because of issues with the AUR package at the time.  Since it's currently not building, can it be returned to the AUR version, and if needed, an interfere added.

**Comment by dr460nf1r3** [comment] 2023-04-08 13:43
> `tilix-git` is using a PKGBUILD from [chaotic-aur/pkgbuild-tilix-git](https://github.com/chaotic-aur/pkgbuild-tilix-git). Looks like it was created because of issues with the AUR package at the time. Since it's currently not building, can it be returned to the AUR version, and if needed, an interfere added?

Yes, I agree on this.

**Comment by xiota** [comment] 2023-04-08 19:38
> > `decaf-emu-git` ... The package cache needs to be cleared because the submodules were recently fixed.
>
> Sources should be cleaned and the package built successfully.

Log still shows same error today.  How to clean the sources?  Manual intervention required?

**Comment by dr460nf1r3** [comment] 2023-04-08 19:46
Actually, this should happen automatically since https://github.com/chaotic-aur/toolbox/commit/15cb300ea48ee77ad1a2430b6efd61ac0e4afb4f, though this package gets built on an HPC which works slightly differently than our "regular" builders. I thought I dropped the source cache of it yesterday :eyes: 
@thotypous or @PedroHLC one of you guys have time to look into it?

**Comment by PedroHLC** [comment] 2023-04-08 19:56
> one of you guys have time to look into it?

Deleted it from c22 and c19. Should be fine now.

**Comment by xiota** [comment] 2023-04-09 07:48
The date stamp on `decaf-emu-git` log changed, but the [log](https://builds.garudalinux.org/repos/chaotic-aur/logs/decaf-emu-git.log) is still showing the same error.
```
==> ERROR: /home/main-builder/pkgsrc/cnl is not a clone of https://github.com/johnmcfarlane/cnl
```
Any idea what is going on?

**Comment by dr460nf1r3** [comment] 2023-04-09 08:38
My guess would be another `cXX` still having the cache. I moved it to `chaotic-dragon` where cache cleaning is ensured.

**Comment by xiota** [comment] 2023-04-18 16:06
Some packages fail checks, like [rofi-lbonn-wayland.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/rofi-lbonn-wayland.log).  Is there a way to make a `PKGBUILD` skip checks by default unless `--check` is passed to `makepkg`?

**Comment by dr460nf1r3** [comment] 2023-04-18 17:13
We can omit the checks by replacing the `check()` function via interfere & `PKGBUILD.append`, like this: https://github.com/chaotic-aur/interfere/blob/1a4b421b7f6fdfcf07655e77531af9713565e23d/guestfs-tools/PKGBUILD.append#L1

**Comment by FabioLolix** [comment] 2023-04-18 17:17
What's going on on rofi-lbonn-wayland ?

```
[10/137] Compiling C object subprojects/libnkutils/nk-git-version.p/src_git-version.c.o
../rofi/subprojects/libnkutils/src/git-version.c: In function â€˜_nk_git_version_run_gitâ€™:
../rofi/subprojects/libnkutils/src/git-version.c:134:5: warning: â€˜g_spawn_check_exit_statusâ€™ is deprecated: Use 'g_spawn_check_wait_status' instead [-Wdeprecated-declarations]
  134 |     if ( ! g_spawn_check_exit_status(status, &error) )
      |     ^~
In file included from /usr/include/glib-2.0/glib.h:84,
```

IMO check failures should be investigated (almost always if it isn't an extreme hassle)

**Comment by xiota** [comment] 2023-04-18 17:30
> ... replacing the `check()` function via interfere... check failures should be investigated...

Other packages have similar issues.  Would prefer upstream fix or upstream PKGBUILD bypass checks.

For rofi-lbonn-wayland, the PKGBUILD maintainer hasn't acted on the check error in ~7 months.  I don't see a related issue in the github, so will open one shortly.

**Comment by xiota** [comment] 2023-05-07 01:48
`vte3-git` builds in clean chroot on my machine, but fails with:
```
==> Starting pkgver()...
fatal: not a git repository (or any of the parent directories): .git
==> ERROR: A failure occurred in pkgver().
```

**Comment by dr460nf1r3** [comment] 2023-05-07 17:53
> `unflac` also builds on my machine, but fails with with a truncated log [unflac.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/unflac.log).

This usually happens when something about the PKGBUILD is not okay. In this case, I found [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=unflac#n31) to be the cause. Probably need to alter the function in order to pass our builders.
No luck in finding the cause for the second one yet, looks like a toolbox bug to me.

**Comment by xiota** [comment] 2023-05-07 22:01
Sorry I missed that...  New [unflac.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/unflac.log) indicates successful build.  Did you bypass `check()`?  I don't see an interfere.

**Comment by xiota** [comment] 2023-05-08 06:33
`qlog-git` aur has been updated, but isn't rebuilding.  Log file date is 2023-05-04.

**Comment by dr460nf1r3** [comment] 2023-05-09 11:28
> `qlog-git` aur has been updated, but isn't rebuilding. Log file date is 2023-05-04.

Is this one on `ufscar-hpc` by chance?

**Comment by xiota** [comment] 2023-05-09 11:50
> Is this one on ufscar-hpc by chance?

Yes, it is.  I've noticed some other packages also aren't updating.  I guess ufscar-hpc is having problems?  Is this something that will eventually be fixed, or will packages need to be manually bumped for the foreseeable future?

**Comment by dr460nf1r3** [comment] 2023-05-11 06:00
Lets see whether this solved the issue: https://github.com/chaotic-aur/packages/issues/2459#issuecomment-1542535361

**Comment by xiota** [comment] 2023-05-18 10:50
@Edu4rdSHL  `nvidia-vaapi-driver-git` has been merged into `libva-nvidia-driver-git`. [PRQ#40508](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/Q3JRHAZWNJFOTJI43G2COGECU3NZKZAY/#XQSW33EQTE5S63NI7WT7LFGJO36N2AZ6)

**Comment by xiota** [comment] 2023-08-29 00:16
@Edu4rdSHL `zenstates` in `CatBuilder/hourly.txt` doesn't exist.  AUR has `zenstates-git` and `zenstates-openrc`.

**Comment by Edu4rdSHL** [comment] 2023-08-29 00:21
@xiota ty for notifying, fixed in https://github.com/chaotic-aur/packages/commit/1696906bba55e45731f6b331a11e6fc35f008f7c

**Closed** 2023-12-01 04:08 UTC
Labels: bug:misc, to-do
