### ISSUE TITLE
[Request] proton-vpn-gtk-app

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#3171] opened 2024-05-25 02:51 UTC
### Package:

https://aur.archlinux.org/packages/proton-vpn-gtk-app

### Purpose:

proton vpn app maintained by the community

### Benefits:

anonymity 

### Building:

package made by amethyst aur helper, contains many aur dependencies

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment] 2024-05-25 02:55
Duplicate of #3167

**Closed by Technetium1** 2024-05-25 02:55 UTC
Labels: invalid:duplicate, request:new-pkg
