### ISSUE TITLE
[Request] JRE

### ISSUE THREAD

**Issue by arthurflor23** [chaotic-aur/packages#1400] opened 2022-04-25 21:57 UTC
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/jre

### Utility this package has for you

It is a package of everything necessary to run a compiled Java program.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment] 2022-04-29 01:04
This is a duplicate of https://github.com/chaotic-aur/packages/issues/1399

**Closed by Technetium1** 2022-04-29 01:04 UTC
Labels: invalid:duplicate, request:new-pkg
