### ISSUE TITLE
[Bug] description

### ISSUE THREAD

**Issue by tgeek77** [chaotic-aur/packages#2639] opened 2023-07-11 11:31 UTC
### Packages:

https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst
https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst

### Latest chaotic version

Unknown

### What happens?

These packages are signed by key: 349BC7808577C592? however, [the instructions](https://aur.chaotic.cx/) refer to key: 3056513887B78AEB.

Error:

```
pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
:: Retrieving packages...
 chaotic-keyring                                                                 28.6 KiB   101 KiB/s 00:00 [################################################################] 100%
 chaotic-mirrorlist                                                               4.1 KiB  10.9 KiB/s 00:00 [################################################################] 100%
loading packages...
:: Import PGP key 349BC7808577C592? [Y/n] 
error: '/var/cache/pacman/pkg/chaotic-mirrorlist.pkg.tar.zst': invalid or corrupted package (PGP signature)
```

### What is expected to happen?

The packages should be added without error.

### Logs

See error output above

### More information

I am attempted to add the Chaotic-AUR repo to a new Arch system. There shouldn't be any kind of issue with existing packages.

**Comment by dr460nf1r3** [comment] 2023-07-11 12:20
Duplicate of https://github.com/chaotic-aur/toolbox/issues/86#issuecomment-1630621807

**Closed by dr460nf1r3** 2023-07-11 12:20 UTC
Labels: bug:misc
