### ISSUE TITLE
[Bug] prboom-plus. No OpenGL!

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#2165] opened 2022-12-14 14:33 UTC
### What happens?

No OpenGL support, can't be chosen as an option.

### What is expected to happen?

OpenGL should be an option.

### More information

Do the following:

0. Install `prboom-plus`.
1. Launch it with an IWAD (if you don't own Doom, get Freedoom!)
2. ESC > Options > General > Video Mode. OpenGL should be an option, perhaps it's not compiled in?

Also, when you launch `prboom-plus` for the first time, mute your speakers and change the MIDI Device to smth that's NOT "SDL". Otherwise you'll get earraped. Then restart the game.

**Comment by Technetium1** [comment] 2022-12-14 16:54
@yum13241 can you please [open an issue upstream](https://github.com/coelckers/prboom-plus/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and link to this issue? I don't see compile flags relating to OpenGL anywhere. There are not any big differences in https://aur.archlinux.org/packages/prboom-plus-um-git

Earrape problem might warrant a second separate issue.

**Comment by yum13241** [comment] 2022-12-15 09:24
What the earrape problem does is loop sounds even after they're supposed to stop. So shooting the pistol will sound like POWPOWPOWPOWPOWPOWPOWPOWPOWPOWPOWPOWPOW... instead of just POW!

**Comment by yum13241** [comment] 2022-12-15 09:51
Ask @Technetium1, I have nothing to do with the building process.

If the package on the AUR [prboom-plus](https://aur.archlinux.org/pkgbase/prboom-plus) is outdated, bug them and flag it as outdated.

**Comment by Technetium1** [comment] 2022-12-15 22:08
@fabiangreffrath both are at 2.6.2:
```
chaotic-aur/prboom-plus 2.6.2-1
chaotic-aur/prboom-plus-um-git 2.6.2.r53.gbfe08a0f-1
```

---

@yum13241 the sound issue seems like it qualifies as a valid bug to fix, rather than a feature request. If it fails the same on DSDA-Doom, definitely open the bug report there instead!

**Comment by yum13241** [comment] 2022-12-20 18:01
The bug does NOT happen in DSDA-Doom.

I opened the bug report on PrBoom+'s github a few days back.

**Comment by fabiangreffrath** [comment] 2022-12-21 11:23
An OpenGL implementation must be Ach l available at build time for the OpenGL renderer. 

> I opened the bug report on PrBoom+'s github a few days back.

Which one?

**Comment by Technetium1** [comment] 2022-12-21 20:38
Build log: [prboom-plus.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/prboom-plus.log) 
Should be `libglvnd`

**Comment by fabiangreffrath** [comment] 2022-12-21 20:50
> OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.

This is a lie:

> -- Found OpenGL: /usr/lib/libOpenGL.so

Could you please apply this patch? 

https://github.com/coelckers/prboom-plus/commit/921adf17e02408e7f0a06b59df4a4c07d716ee35

**Comment by xiota** [comment] 2023-09-15 05:33
Has this been resolved?  Looks like `prboom-plus` has had a few updates since this was opened.
```
$ pacman -Ss prboom-plus
chaotic-aur/prboom-plus 2.6.66-1
    An advanced, Vanilla-compatible Doom engine based on PrBoom
chaotic-aur/prboom-plus-um-git 2.6.66.r0.g96951516-1
    An advanced, Vanilla-compatible Doom engine based on PrBoom. Includes support for UMAPINFO
```

**Comment by fabiangreffrath** [comment] 2023-09-15 06:29
Why does this have two packages? The `2.6.66` tag has been applied to the `96951516` git commit and the repository has been closed since then. There are no further commits and the contents of both packages are identical.

**Comment by xiota** [comment] 2023-09-15 08:03
@fabiangreffrath  No idea.  Looking for old issues that can be closed.  Can you test whether `dsda-doom` and `dsda-doom-git` have the same issue?  If one of them doesn't, would there be any reason to keep `prboom-plus*`, since `dsda-doom` is a fork?

**Comment by fabiangreffrath** [comment] 2023-09-15 08:09
Well, dsda-coom is in active development, so there is actually a difference between releases and git snapshots. prboom-plus is dead and won't be maintained any further. I have already replaced it with dsda-doom in Debian.

**Comment by fabiangreffrath** [comment] 2023-09-15 09:33
The release might still be relevant to some, but the git snapshot can be dropped.

**Comment by xiota** [comment] 2023-09-15 09:40
Since development on `prboom-plus` has ceased, this issue will most likely never be resolved.  So closing this as not planned.

`prboom-plus-um-git` has been dropped, since it's essentially a duplicate of `prboom-plus`, which will be kept for now.

**Closed by xiota** 2023-09-15 09:40 UTC
Labels: bug:misc
