### ISSUE TITLE
[Rebuild] neovim-git

### ISSUE THREAD

**Issue by roland-5** [chaotic-aur/packages#2904] opened 2023-11-16 12:08 UTC
### Packages:

https://aur.archlinux.org/packages/neovim-git

### Latest chaotic version

0.9.0.r2209.g610f50ddaf-1

### Reason for rebuild

I asked about it previously [here](https://github.com/chaotic-aur/packages/discussions/2903).
There has been no new builds of Neovim for several days from chaotic, even though there are changes in the Neovim repository. 
I have gimp-git installed and every time there is a change in the repository, after building on the chaotic server there is a new build to install, but not from Neovim. These are the only applications with the git extension I have.

### Builds?

[neovim-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/neovim-git.log)

**Comment by roland-5** [comment] 2023-11-17 01:58
@xiota @dr460nf1r3 New builds are available to download and install. Thank you very much, both for you.
Should I close this issue or you need it still to check on something?

**Comment by xiota** [comment] 2023-11-17 02:05
If there are any more problems with this package, please comment here.

**Comment by xiota** [comment] 2023-12-04 20:21
@dr460nf1r3  Looks like ufscar hasn't built anything since 2023-11-28.

**Comment by dr460nf1r3** [comment] 2023-12-08 19:35
This has supposedly just been fixed by @PedroHLC !

**Comment by roland-5** [comment] 2024-01-30 14:34
Is everything good? Last build is v0.10.0-dev-2196+g1e0996b572 and this commit was [5 days ago](https://github.com/neovim/neovim/commit/1e0996b57230ad65c28659e179a7da7bfa01e5be).

**Comment by Technetium1** [comment] 2024-02-01 20:41
A new dep was added

**Closed** 2024-02-01 20:42 UTC
Labels: request:rebuild-pkg, priority:high

**Comment by roland-5** [comment] 2024-02-27 02:19
I hate to be **_this_** guy, but I got `nvim: symbol lookup error: nvim: undefined symbol: ts_set_allocator` error when I try launch `Neovim` and I don't see any new builds, even though new commits appear in Neovim git repository, so `treesitter-git` probably broke something. @Technetium1 @xiota or @dr460nf1r3 if any of you would have the time and opportunity to come back in the future to this and check this out, I would appreciate it.

**Comment by roland-5** [comment] 2024-02-27 02:56
`neovim-git-0.10.0.r2457.ga4b4442524-1` fixed this. Thank you!

**Comment by xiota** [comment] 2024-02-27 03:04
@roland-5 It's not really fixed yet... The problem is changes in `tree-sitter-git` that removed access to the function.

Going to open an issue at [github/neovim](https://github.com/neovim/neovim).  Consider adding `tree-sitter-git` and `neovim-git` in `IgnorePkg` in `pacman.conf` until it's fixed.

**Comment by roland-5** [comment] 2024-02-28 08:32
@xiota That's more than great. Thank you so much for help and sorry for the trouble!
