### ISSUE TITLE
Issues when installing package groups?

### ISSUE THREAD

**Issue by drishal** [chaotic-aur/packages#706] opened 2021-06-27 05:33 UTC
when  I am installing some popular package groups like `gnome` or `kde-applications` I get some weird conflict issues due to which either the installation of packages fails, or gets replaced by a `-git` version which could be potentially buggy
For eg when I do `sudo pacman -S gnome` it fails with `gdm-plymouth and gdm-prime are in conflict`. Maybe either resolve these conflicts by removing the conflicting packages or renaming those groups to something like `gnome-chaotic` or `kde-chaotic`

**Comment by dr460nf1r3** [comment] 2021-06-27 08:40
Related to #542

**Comment by PedroHLC** [comment] 2021-08-08 18:36
Closing this, duplicate of #542

**Closed** 2021-08-08 18:41 UTC
Labels: duplicate
